//! Generator to produce all Turing machines (permutations) for the given number of states.  
//! While this works it is highly inefficient to check every single machine. This can be used
//! at most until BB4. \
//! It mostly exists to validate the logic and results of GeneratorReduced during development.
//!
//! How it works: \
//! First the initial [transition_table] is created (stack), filled with 0RA as first element for each transition.
//! Also the list of transitions to cycle through is created [tr_permutations], holding the (4n+1) elements.
//! In each cycle one [Permutation] is created, holding the id (starting with 0) and the transition table
//! and stored in [permutations] (heap). \
//! Because only two bytes are used for each transition, this results in a small array which can be copied
//! extremely fast. \
//! During each cycle (usually) only one transition is changed in the transition table,
//! thus minimizing the changed data.
//! After all transitions have been created or the block size is reached, the permutations are returned (moved). \
//!
//! There are two generation option: front or back:
//! - front: Field A0 is rotated first (then A1, B0, B1, C0 etc.) or
//! - back: The last field is rotated first, e.g. for BB5: E1, then E0, D1, D0, C1 etc.
//!
//! Since this is a calculable regular pattern, it is possible to break the permutation generation
//! into several batches and addressing a batch directly (it is not required to create all the
//! permutations up to that batch). This is used to parallelize permutation generation and
//! subsequently the deciders to run in multiple threads.

use crate::{
    config::{Config, MAX_STATES},
    data_provider::{
        generator::{
            create_all_transition_permutations, num_turing_machine_permutations, Generator,
        },
        DataProvider, DataProviderBatch, DataProviderThreaded, ResultDataProvider,
    },
    decider::decider_result::{EndReason, PreDeciderCount},
    machine::Machine,
    pre_decider::PreDeciderRun,
    transition_symbol2::{TransitionSymbol2, TransitionTableSymbol2},
};

const BATCH_SIZE_REQUEST_SINGLE_THREAD_MAX: usize = 500_000;

/// This generator creates all permutations of transition sets (Turing machine) possible for the given n_states,
/// where 'hold' is limited to this one transition: '---'. This results in (4n+1)^2n combinations. \
/// The transition table is generated by permuting all transition permutations for field A0, then A1, then B0 and so on.
pub struct GeneratorFull {
    /// Next id for the generated machine, starting with 0.
    id_next: u64,
    /// batch_no, increased for every call, batch 0 will show batch 1
    batch_no: usize,
    /// The number of states used for this generator.
    // n_states: usize,
    /// The total number of machines to be generated.
    n_machines: u64,
    /// The reduced actual batch size (number of Turing machines generated in each call).
    batch_size: usize,
    /// The given limit of machines to generate or (if smaller) the maximum number of machines for the number of states.
    limit: u64,
    /// The total number of batches to create all permutations.
    num_batches: usize,
    /// The (4n+1) permutations for the transitions
    tr_permutations: Vec<TransitionSymbol2>,
    /// The transition set for one Turning machine. Will be adjusted each round and copied to the machine permutation.
    transition_table: TransitionTableSymbol2,
    /// Number of fields in the transition table (including the 2 empty fields for dummy state 0).
    n_fields: usize,
    /// Stores the id of the current transition permutation for the corresponding transition field.
    fields: [usize; (MAX_STATES + 1) * 2],
    field_no: usize,
    n_states: usize,
    /// Sets if the first field A0 is rotated first (then A1, B0, B1, C0 etc.) or
    /// the last field (BB5: E1, then E0, D1, D0, C1 etc.)
    is_first_rotate_field_forward: bool,
}

impl GeneratorFull {
    /// Creates a new generator \
    /// batch_size_request: max machines for each batch \
    /// limit: max total machines to generate, use 0 without limit
    pub fn new(config: &Config) -> Self {
        let n_states = config.n_states();
        assert!(n_states <= 7, "This generator can not create all permutations for {n_states} states as this would exceed u64:MAX permutations.");
        let tr_permutations = create_all_transition_permutations(n_states);
        let mut transition_table = TransitionTableSymbol2::new_default(n_states);
        // set all in set to the first variant
        transition_table.transitions[2..2 + n_states * 2].fill(tr_permutations[0]);
        let n_machines = num_turing_machine_permutations(n_states) as u64;
        let limit = if config.machines_limit() > 0 {
            config.machines_limit().min(n_machines)
        } else {
            n_machines
        };
        let batch_size =
            Self::calc_batch_size(config.generator_batch_size_request_full(), n_states);
        // let num_batches = ((limit + batch_size as u64 - 1) / batch_size as u64) as usize;
        let num_batches = limit.div_ceil(batch_size as u64) as usize;
        let n_fields = 2 * (n_states + 1);

        Self {
            id_next: 0,
            batch_no: 0,
            n_machines,
            batch_size,
            num_batches,
            limit,
            tr_permutations,
            transition_table,
            n_fields,
            fields: [0; (MAX_STATES + 1) * 2],
            field_no: if config.generator_first_rotate_field_front() {
                4
            } else {
                n_fields - 3
            },
            n_states,
            is_first_rotate_field_forward: config.generator_first_rotate_field_front(),
        }
    }

    fn calc_batch_init(&mut self, batch_no: usize) {
        // if batch_no == 0 {
        //     // self.id_next = 0;
        //     // self.fields.fill(0);
        //     return;
        // }        self.batch_no += 1;
        self.batch_no = batch_no;
        self.id_next = batch_no as u64 * self.batch_size as u64;
        // fields 0 and 1 are unused
        // fields 2 and 3 will be 0 as this is guaranteed by the batch size (status A always fully permuted)
        // calculating the remaining fields
        let permutations = (4 * self.n_states + 1) as u64;
        let mut remain = self.id_next / (permutations * permutations);
        // reset transitions, only the used ones will be filled in the following loop, possibly redundant
        self.transition_table.transitions[2..self.n_states * 2 + 2].fill(self.tr_permutations[0]);
        // if self.transition_table.transitions[7].transition != 194 {
        //     println!("{}", self.batch_no);
        //     todo!()
        // }
        if self.is_first_rotate_field_forward {
            // field_no is always 4
            let mut i = 4;
            loop {
                if remain > 0 {
                    let m = remain % permutations;
                    self.fields[i] = m as usize;
                    self.transition_table.transitions[i] = self.tr_permutations[self.fields[i]];
                    i += 1;
                    remain = (remain - m) / permutations;
                } else {
                    break;
                }
            }
        } else {
            let mut i = self.n_fields - 3;
            loop {
                if remain > 0 {
                    let m = remain % permutations;
                    self.fields[i] = m as usize;
                    self.transition_table.transitions[i] = self.tr_permutations[self.fields[i]];
                    i -= 1;
                    remain = (remain - m) / permutations;
                } else {
                    break;
                }
            }
        }
    }

    /// Returns the next batch of permutations and an info if this is the last batch.
    /// This is the core logic of the generator.
    fn generate_permutation_batch_next_forward(&mut self) -> (Vec<Machine>, bool) {
        if self.id_next >= self.n_machines {
            return (Vec::new(), true);
        }

        // let mut is_last_batch = false;
        let mut permutations = Vec::with_capacity(self.batch_size);
        let num_tr_permutations = self.tr_permutations.len();
        // 'creation: loop {
        loop {
            // permutations state A
            // loop all transitions for first state and its two symbols
            let mut id = self.id_next;
            for v1 in self.tr_permutations.iter() {
                self.transition_table.transitions[3] = *v1;
                for v0 in self.tr_permutations.iter() {
                    self.transition_table.transitions[2] = *v0;
                    let permutation = Machine::new(id, self.transition_table);
                    permutations.push(permutation);
                    id += 1;
                    if id == self.limit {
                        // total maximum reached
                        self.id_next = id;
                        return (permutations, true);
                    }
                }
            }
            self.id_next = id;

            // update line two, permutations state B (still separate for performance)
            self.fields[4] += 1;
            if self.fields[4] < num_tr_permutations {
                self.transition_table.transitions[4] = self.tr_permutations[self.fields[4]];
            } else {
                // set field back to first option
                self.fields[4] = 0;
                self.transition_table.transitions[4] = self.tr_permutations[0];
                'outer: loop {
                    self.field_no += 1;
                    // if self.field_no == self.n_fields {
                    //     // apparently this does not happen. If it happens field_no is off for next batch
                    //     todo!();
                    //     // all variants created
                    //     // is_last_batch = true;
                    //     // println!("last id: {}", self.id_next);
                    //     break 'creation;
                    // }
                    self.fields[self.field_no] += 1;
                    if self.fields[self.field_no] < num_tr_permutations {
                        // set next field with next permutation
                        self.transition_table.transitions[self.field_no] =
                            self.tr_permutations[self.fields[self.field_no]];
                        loop {
                            self.field_no -= 1;
                            if self.field_no == 4 {
                                break 'outer;
                            } else {
                                // set previous field back to first option
                                self.fields[self.field_no] = 0;
                                self.transition_table.transitions[self.field_no] =
                                    self.tr_permutations[0];
                            }
                        }
                    }
                }
            }
            if permutations.len() == self.batch_size {
                break;
            }
        }

        (permutations, false)
    }

    /// Returns the next batch of permutations and an info if this is the last batch.
    /// This is the core logic of the generator.
    fn generate_permutation_batch_next_reverse(&mut self) -> (Vec<Machine>, bool) {
        if self.id_next >= self.n_machines {
            return (Vec::new(), true);
        }

        // let mut is_last_batch = false;
        let mut permutations = Vec::with_capacity(self.batch_size);
        let num_tr_permutations = self.tr_permutations.len();
        let first = self.n_fields - 1;
        let third = self.n_fields - 3;
        //
        //     // all variants created
        //     println!("{}", self.batch_no);
        //     todo!();
        //     // is_last_batch = true;
        //     // println!("last id: {}", self.id_next);
        //     break 'creation;
        // }'creation: loop {
        loop {
            // permutations state A
            // loop all transitions for last state and its two symbols
            let mut id = self.id_next;
            for v1 in self.tr_permutations.iter() {
                self.transition_table.transitions[first - 1] = *v1;
                for v0 in self.tr_permutations.iter() {
                    self.transition_table.transitions[first] = *v0;
                    let permutation = Machine::new(id, self.transition_table);
                    permutations.push(permutation);
                    id += 1;
                    if id == self.limit {
                        // total maximum reached
                        self.id_next = id;
                        return (permutations, true);
                    }
                }
            }
            self.id_next = id;

            // update line two, permutations state D for BB5 (still separate for performance)
            self.fields[third] += 1;
            if self.fields[third] < num_tr_permutations {
                self.transition_table.transitions[third] = self.tr_permutations[self.fields[third]];
            } else {
                // set field back to first option
                self.fields[third] = 0;
                self.transition_table.transitions[third] = self.tr_permutations[0];
                'outer: loop {
                    self.field_no -= 1;
                    // if self.field_no == 1 {
                    //     // all variants created
                    //     println!("{}", self.batch_no);
                    //     todo!();
                    //     // is_last_batch = true;
                    //     // println!("last id: {}", self.id_next);
                    //     break 'creation;
                    // }
                    self.fields[self.field_no] += 1;
                    if self.fields[self.field_no] < num_tr_permutations {
                        // set next field with next permutation
                        self.transition_table.transitions[self.field_no] =
                            self.tr_permutations[self.fields[self.field_no]];
                        loop {
                            self.field_no += 1;
                            if self.field_no == third {
                                break 'outer;
                            } else {
                                // set previous field back to first option
                                self.fields[self.field_no] = 0;
                                self.transition_table.transitions[self.field_no] =
                                    self.tr_permutations[0];
                            }
                        }
                    }
                }
            }
            if permutations.len() == self.batch_size {
                break;
            }
        }

        (permutations, false)
    }
}

impl Generator for GeneratorFull {
    /// Returns the next batch of permutations and an info if this is the last batch.
    fn generate_permutation_batch_no(&mut self, batch_no: usize) -> (Vec<Machine>, bool) {
        self.calc_batch_init(batch_no);
        self.generate_permutation_batch_next()
    }

    /// Returns the next batch of permutations and an info if this is the last batch.
    /// This is the core logic of the generator.
    fn generate_permutation_batch_next(&mut self) -> (Vec<Machine>, bool) {
        let r = if self.is_first_rotate_field_forward {
            self.generate_permutation_batch_next_forward()
        } else {
            self.generate_permutation_batch_next_reverse()
        };
        self.batch_no += 1;
        r
    }

    /// The given limit of machines to generate or (if smaller) the maximum number of machines for the number of states.
    fn limit(&self) -> u64 {
        self.limit
    }

    fn pre_decider_count(&self) -> PreDeciderCount {
        PreDeciderCount::default()
    }

    fn check_generator_batch_size_request_single_thread(&mut self) {
        if self.batch_size > BATCH_SIZE_REQUEST_SINGLE_THREAD_MAX {
            // self.config.generator_batch_size_request_full = BATCH_SIZE_REQUEST_SINGLE_THREAD_MAX;
            let batch_size =
                Self::calc_batch_size(BATCH_SIZE_REQUEST_SINGLE_THREAD_MAX, self.n_states);
            // self.num_batches = ((self.limit + batch_size as u64 - 1) / batch_size as u64) as usize;
            self.num_batches = self.limit.div_ceil(batch_size as u64) as usize;
            self.batch_size = batch_size;
        }
    }

    fn num_eliminated(&self) -> u64 {
        0
    }
}

impl DataProvider for GeneratorFull {
    fn name(&self) -> &str {
        "Generator Full"
    }

    fn machine_batch_next(&mut self) -> ResultDataProvider {
        let (machines, is_last_batch) = self.generate_permutation_batch_next();
        // self.batch_no += 1;
        let end_reason = if is_last_batch {
            EndReason::IsLastBatch
        } else {
            EndReason::None
        };
        Ok(DataProviderBatch {
            batch_no: self.batch_no - 1,
            machines,
            pre_decider_count: None,
            end_reason,
        })
    }

    fn batch_size(&self) -> usize {
        self.batch_size
    }

    /// The total number of batches to create all permutations.
    fn num_batches(&self) -> usize {
        self.num_batches
    }

    // fn config(&self) -> &Config {
    //     &self.config
    // }

    fn num_machines_total(&self) -> u64 {
        self.limit
    }

    fn requires_pre_decider_check(&self) -> PreDeciderRun {
        PreDeciderRun::RunStartBRightOnly
    }

    fn returns_pre_decider_count(&self) -> bool {
        false
    }

    fn set_batch_size_for_num_threads(&mut self, num_threads: usize) {
        // TODO fine tune
        if num_threads == 1 {
            self.check_generator_batch_size_request_single_thread();
        }
    }
}

impl DataProviderThreaded for GeneratorFull {
    fn new_from_data_provider(&self) -> Self {
        let mut transition_table = TransitionTableSymbol2::new_default(self.n_states);
        // set all in set to the first variant
        transition_table.transitions[2..2 + self.n_states * 2].fill(self.tr_permutations[0]);

        Self {
            id_next: 0,
            batch_no: 0,
            // n_states: self.n_states,
            n_machines: self.n_machines,
            batch_size: self.batch_size,
            limit: self.limit,
            num_batches: self.num_batches,
            tr_permutations: self.tr_permutations.clone(),
            transition_table,
            n_fields: self.n_fields,
            fields: [0; (MAX_STATES + 1) * 2],
            field_no: if self.is_first_rotate_field_forward {
                4
            } else {
                self.n_fields - 3
            },
            n_states: self.n_states,
            is_first_rotate_field_forward: self.is_first_rotate_field_forward,
        }
    }

    fn batch_no(&mut self, batch_no: usize) -> DataProviderBatch {
        let (machines, is_last_batch) = self.generate_permutation_batch_no(batch_no);
        let end_reason = if is_last_batch {
            EndReason::IsLastBatch
        } else {
            EndReason::None
        };
        DataProviderBatch {
            batch_no: self.batch_no,
            machines,
            pre_decider_count: None,
            end_reason,
        }
    }
}

// pub fn validate_next_with_batch_no() {
//     let n_states = 3;
//     let config = Config::builder(n_states)
//         .generator_full_batch_size_request(10000)
//         // .generator_first_rotate_field_front(true)
//         .build();
//     let mut generator_next = GeneratorFull::new(&config);
//     let mut generator_batch_no = GeneratorFull::new(&config);
//     let (_m_no, _is_finished) = generator_batch_no.generate_permutation_batch_no(484);
//
//     println!("Machines: {}", generator_next.n_machines);
//
//     let mut batch_no = 0;
//     let mut counter = 0;
//     loop {
//         let (m_next, is_finished) = generator_next.generate_permutation_batch_next();
//         // delete known transition data to force update
//         for i in 2..8 {
//             generator_batch_no.transition_table.transitions[i].transition = 0;
//         }
//         let (m_no, _is_finished) = generator_batch_no.generate_permutation_batch_no(batch_no);
//         println!("batch_no {}, size {}", batch_no + 1, m_next.len());
//
//         for (i, m) in m_next.iter().enumerate() {
//             let mv = &m_no[i];
//             counter += 1;
//             assert_eq!(m, mv);
//         }
//
//         if is_finished {
//             assert_eq!(counter, generator_next.n_machines);
//             break;
//         }
//
//         batch_no += 1;
//     }
//     // let result = batch_run_decider_chain_data_provider_single_thread(&vec![dc], generator);
//     // println!("{}", result);
//     // println!("{}", result.machines_max_steps_to_string(10));
//     // assert_eq!(result_max_steps_known(n_states), result.steps_max());
//     println!();
// }

/// run this only in release mode from command line: \
/// cargo test --release generator_full
#[cfg(test)]
mod tests {
    use crate::{
        decider::decider_engine::{
            batch_run_decider_chain_data_provider_single_thread,
            batch_run_decider_chain_threaded_data_provider_multi_thread,
        },
        decider::decider_result::result_max_steps_known,
        decider::DeciderStandard,
    };

    use super::*;

    const USE_FRONT: bool = true;

    #[test]
    fn decider_generator_full_bb2() {
        run_test_decider_generator_full(2);
    }

    #[test]
    fn decider_generator_full_bb3() {
        run_test_decider_generator_full(3);
    }

    /// run this only in release mode from command line: \
    /// cargo test --release test_decider_generator_full_bb4
    #[test]
    fn decider_generator_full_bb4() {
        run_test_decider_generator_full(4);
    }

    /// run this only in release mode from command line: \
    /// cargo test --release test_decider_generator_full_threaded_bb4
    #[test]
    fn decider_generator_full_bb4_threaded() {
        run_test_decider_generator_full_threaded(4);
    }

    #[test]
    fn generator_full_direct_access_batch_no() {
        let config = Config::builder(4)
            .generator_first_rotate_field_front(USE_FRONT)
            .generator_full_batch_size_request(10_000)
            .machine_limit(10_000_000)
            .build();
        let m1;
        let mut batch_no = 0;
        let mut g = GeneratorFull::new(&config);
        loop {
            let (vm, is_finished) = g.generate_permutation_batch_next();
            if is_finished {
                m1 = vm.first().unwrap().clone();
                break;
            }
            batch_no += 1;
        }

        // check direct batch access
        let mut g = GeneratorFull::new(&config);
        let (vm, _) = g.generate_permutation_batch_no(batch_no);
        let m2 = vm.first().unwrap().clone();
        assert_eq!(m1, m2);
        // println!("m1: {}", m1);

        // check exact permutation
        if USE_FRONT {
            let id = 9993042;
            let mut transitions: Vec<(&str, &str)> = Vec::new();
            transitions.push(("0RA", "0RA"));
            transitions.push(("0RA", "1LB"));
            transitions.push(("0RA", "1RD"));
            transitions.push(("0RA", "0RA"));
            let m = Machine::from_string_tuple(id, &transitions);
            assert_eq!(m1, m);
        }
    }

    #[test]
    fn generator_full_direct_access_batch_no_all() {
        let config = Config::builder(3)
            .generator_first_rotate_field_front(USE_FRONT)
            .generator_full_batch_size_request(10_000)
            // .machine_limit(10_000_000)
            .machine_limit(0)
            .build();
        let mut m1;
        let mut batch_no = 0;
        let mut g1 = GeneratorFull::new(&config);
        let mut g2 = GeneratorFull::new(&config);
        loop {
            let (vm1, is_finished) = g1.generate_permutation_batch_next();
            m1 = vm1.first().unwrap();
            // check direct batch access
            let (vm2, _) = g2.generate_permutation_batch_no(batch_no);
            let m2 = vm2.first().unwrap();
            // print!("{batch_no}, ");
            assert_eq!(m1, m2);
            assert_eq!(vm1.len(), vm2.len());
            if is_finished {
                break;
            }
            batch_no += 1;
        }

        // println!("m1: {}", m1);
    }

    fn run_test_decider_generator_full(n_states: usize) {
        let config = config_bench(n_states, USE_FRONT);
        let dc = DeciderStandard::Cycler.decider_config(&config);
        let generator = GeneratorFull::new(&config);
        let result = batch_run_decider_chain_data_provider_single_thread(&vec![dc], generator);
        println!("{}", result);
        println!("{}", result.machines_max_steps_to_string(10));
        assert_eq!(result_max_steps_known(n_states), result.steps_max());
    }

    fn run_test_decider_generator_full_threaded(n_states: usize) {
        let config = config_bench(n_states, USE_FRONT);
        let dc = DeciderStandard::Cycler.decider_config(&config);
        let generator = GeneratorFull::new(&config);
        let result =
            batch_run_decider_chain_threaded_data_provider_multi_thread(&vec![dc], generator);
        // println!("{}", result);
        assert_eq!(result_max_steps_known(n_states), result.steps_max());
    }

    fn config_bench(n_states: usize, front: bool) -> Config {
        let limit = if front { 200_000_000 } else { 1_550_000_000 };
        Config::builder(n_states)
            .generator_first_rotate_field_front(front)
            // .generator_batch_size_request_full(GENERATOR_BATCH_SIZE_REQUEST_FULL)
            // .generator_batch_size_request_reduced(GENERATOR_BATCH_SIZE_REQUEST_REDUCED)
            .machine_limit(limit)
            // .step_limit_cycler(110)
            // .cpu_utilization(100)
            .build()
    }
}
