// TODO flip states: A0 -> 0RB,1RB, B0 -> A,B,C (not D, E?)

#[cfg(feature = "bb_generator_longest_skip_chain")]
use crate::machine_info::MachineInfo;
use crate::{
    config::{Config, MAX_STATES},
    data_provider::{DataProvider, DataProviderBatch, DataProviderThreaded, ResultDataProvider},
    decider_result::{EndReason, PreDeciderCount},
    generator::{self, create_all_transition_permutations, Generator},
    machine::Machine,
    pre_decider::{
        check_not_all_states_used, check_only_one_direction, check_only_zero_writes,
        check_simple_start_cycle, count_hold_transitions, PreDeciderRun,
    },
    status::PreDeciderReason,
    transition_symbol2::{TransitionSymbol2, TransitionTableSymbol2, TRANSITIONS_FOR_A0},
};

const BATCH_SIZE_REQUEST_SINGLE_THREAD: usize = 1_000_000;

/// This generator creates all combinations of transition sets (Turing machine) which match certain criteria for the given n_states,
/// where halt is limited to one transition ('---'). This results far less then the (4n+1)^2n combinations. \
/// The normal routine is to generate a machine, run it through the deciders, having a lot of machines already filtered out by the
/// pre-deciders and evaluate the result to find the challenging machines.
/// This means the machine has to be created, stored in heap memory and the evaluated. It is much faster, to
/// * either not create the machine at all, meaning the generator is not even running over this permutation
/// * or eliminate it by checking pre-decider rules on stack memory and without copying the data first.
///
/// The transition table is generated by permuting all transition permutations for field A0, then A1, then B0 and so on. \
/// The regular pattern of the normal generation allows to break the permutation generation into several batches and addressing a batch directly (so
/// it is not required to create the permutations up to that batch). This can also be used to parallelize permutation generation here, but
/// the resulting batch will be much smaller and its size cannot be determined.
///
/// Elimination Rule
// TODO possibly faster if pre-decider could be identified which do not rely on A0 and A1, then the full block could be eliminated. \
// But generator is not really the time issue.
pub struct GeneratorReduced {
    /// Next id for the generated machine, starting with 0.
    id_next: u64,
    // id_batch_start: u64,
    id_batch_last: u64,
    batch_no: usize,
    /// The number of states used for this generator.
    // n_states: usize,
    /// The total number of machines to be generated.
    n_machines: u64,
    /// The reduced actual batch size (number of Turing machines generated in each call).
    batch_size: usize,
    /// The given limit of machines to generate or (if smaller) the maximum number of machines for the number of states.
    limit: u64,
    /// The total number of batches to create all permutations.
    num_batches: usize,
    /// The (4n+1) permutations for the transitions
    tr_permutations: Vec<TransitionSymbol2>,
    /// The reduced set of permutations for A0 (no hold, no direction left)
    // tr_permutations_a0: Vec<TransitionSymbol2>,
    /// The transition set for one Turning machine. Will be adjusted each round and copied to the machine permutation.
    transition_table: TransitionTableSymbol2,
    /// Number of fields in the transition table (including the 2 empty fields for dummy state 0).
    n_fields: usize,
    /// Stores the id of the current transition permutation for the transition field.
    fields: [usize; (MAX_STATES + 1) * 2],
    field_no: usize,
    pre_decider_count_batch: PreDeciderCount,
    // pre_decider_count_total: PreDeciderCount,
    n_states: usize,
    #[cfg(feature = "bb_generator_longest_skip_chain")]
    longest_skip_chain: Counter,
}

impl GeneratorReduced {
    /// Creates a new generator \
    /// batch_size_request: max machines for each batch \
    /// limit: max total machines to generate, use 0 without limit
    pub fn new(config: &Config) -> Self {
        let n_states = config.n_states();
        assert!(n_states <= 7, "This generator can not create all permutations for {n_states} states as this would exceed u64:MAX permutations.");
        let tr_permutations = create_all_transition_permutations(n_states);
        // let tr_permutations_a0 = filter_all_transition_permutations_for_a0(&tr_permutations);
        // let tr_permutations_a0 = TRANSITIONS_FOR_A0;
        let mut transition_table = TransitionTableSymbol2::new_default(n_states);
        // set all in set to the first variant
        transition_table.transitions[2..2 + n_states * 2].fill(tr_permutations[0]);
        let n_machines = generator::num_turing_machine_permutations(n_states) as u64;
        let limit = if config.machines_limit() > 0 {
            config.machines_limit().min(n_machines)
        } else {
            n_machines
        };
        let batch_size =
            Self::calc_batch_size(config.generator_batch_size_request_reduced(), n_states);
        // let num_batches = ((limit + batch_size as u64 - 1) / batch_size as u64) as usize;
        let num_batches = limit.div_ceil(batch_size as u64) as usize;

        Self {
            id_next: 0,
            // id_batch_start: 0,
            id_batch_last: 0,
            batch_no: 0,
            // n_states,
            n_machines,
            batch_size,
            num_batches,
            limit,
            tr_permutations,
            // tr_permutations_a0,
            transition_table,
            n_fields: 2 * (n_states + 1),
            fields: [0; (MAX_STATES + 1) * 2],
            field_no: 4,
            pre_decider_count_batch: Default::default(),
            // pre_decider_count_total: Default::default(),
            n_states: config.n_states(),
            #[cfg(feature = "bb_generator_longest_skip_chain")]
            longest_skip_chain: Default::default(),
        }
    }

    // TODO merge with GeneratorFull?
    fn calc_batch_init(&mut self, batch_no: usize) {
        if batch_no == 0 {
            // self.id_next = 0;
            // self.fields.fill(0);
            return;
        }
        self.id_next = batch_no as u64 * self.batch_size as u64;
        // fields 0 and 1 are unused
        // fields 2 and 3 will be 0 as this is guaranteed by the batch size (status A always fully permuted)
        // calculating the remaining fields
        // let mut remain = (batch_no as u64 - 1) * self.batch_size as u64;
        let permutations = (4 * self.n_states + 1) as u64;
        let mut remain = self.id_next / (permutations * permutations);
        let mut i = 4;
        loop {
            if remain > 0 {
                let m = remain % permutations;
                self.fields[i] = m as usize;
                self.transition_table.transitions[i] = self.tr_permutations[self.fields[i]];
                i += 1;
                remain = (remain - m) / permutations;
            } else {
                break;
            }
        }
        // field_no is always 4
    }

    // #[allow(non_snake_case)]
    // fn calc_left_out_until_0RB(&self) -> u64 {
    //     // Leaving out 0RA and 0RB
    //     2u64.pow(2 * self.n_states as u32)
    // }

    #[inline]
    pub fn check_pre_decider(&self) -> PreDeciderReason {
        let tr_used = self.transition_table.transitions_used(self.n_states);
        // if count_hold_transitions(tr_used) != 1 {
        //     todo!("should not happen");
        //     return PreDeciderReason::NotExactlyOneHoldCondition;
        // }
        if check_only_one_direction(tr_used) {
            return PreDeciderReason::OnlyOneDirection;
        }
        if check_only_zero_writes(tr_used) {
            return PreDeciderReason::WritesOnlyZero;
        }
        // let old = check_not_all_states_used(&self.transition_table, self.n_states);
        // let new = check_not_all_states_used_new(&self.transition_table, self.n_states);
        // if old != new && old {
        //     println!(
        //         "Mismatch for {}, old: {old}, new: {new}",
        //         self.transition_table.to_standard_tm_text_format()
        //     );
        // }
        if check_not_all_states_used(&self.transition_table, self.n_states) {
            return PreDeciderReason::NotAllStatesUsed;
        }
        if check_simple_start_cycle(&self.transition_table) {
            return PreDeciderReason::SimpleStartCycle;
        }

        PreDeciderReason::None
    }

    fn id_batch_start(&self) -> u64 {
        self.id_batch_last / self.batch_size as u64 * self.batch_size as u64
    }
}

impl Generator for GeneratorReduced {
    /// Create new generator for random batch no. \
    /// Avoids some recalculations for e.g. batch_size, but is like new.
    fn new_from_generator_deprecated(&self) -> Self {
        self.new_from_data_provider()
    }

    /// Returns the next batch of permutations and an info if this is the last batch.
    fn generate_permutation_batch_no(&mut self, batch_no: usize) -> (Vec<Machine>, bool) {
        self.calc_batch_init(batch_no);
        self.generate_permutation_batch_next()
    }

    /// Returns the next batch of permutations and an info if this is the last batch.
    fn generate_permutation_batch_next(&mut self) -> (Vec<Machine>, bool) {
        if self.id_next >= self.n_machines {
            return (Vec::new(), true);
        }
        // println!("Generator reduced: is_next = {}", self.id_next);
        self.id_batch_last = (self.id_next + self.batch_size as u64 - 1).min(self.limit - 1);
        self.pre_decider_count_batch = PreDeciderCount::default();

        let mut is_last_batch = false;
        let mut permutations = Vec::with_capacity(self.batch_size);
        let num_tr_permutations = self.tr_permutations.len();
        // let ids_left_out = (self.tr_permutations.len() - self.tr_permutations_a0.len()) as u64;
        let ids_left_out = self.tr_permutations.len() as u64 - 2;
        let mut num_hold_a1;
        let range_3_to_n_states = 4..self.n_states * 2 + 2;
        let mut num_hold_other_lines =
            count_hold_transitions(&self.transition_table.transitions[range_3_to_n_states.clone()]);
        // let ids_not_generated_per_round = ids_left_out * self.tr_permutations.len() as u64;
        // TODO calc left out in one step
        // self.pre_decider_count.num_not_generated = (ids_left_out).pow(2 * self.n_states as u32);
        // let tr_permutations_a0 = TRANSITIONS_FOR_A0;
        // let jump_0rb = self.calc_left_out_until_0RB();
        // self.id_next = self.calc_left_out_until_0RB();
        'creation: loop {
            // permutations state A
            // loop all transitions for first state and its two symbols
            // id must jump 2 to 0RB
            let mut id = self.id_next + 2;
            for v1 in self.tr_permutations.iter() {
                self.transition_table.transitions[3] = *v1;
                num_hold_a1 = v1.is_hold() as usize;
                for v0 in TRANSITIONS_FOR_A0.iter() {
                    self.transition_table.transitions[2] = *v0;
                    let mut permutation = Machine::new(id, self.transition_table);
                    // if self.pre_decider() == PreDeciderReason::None {
                    //     permutation.set_eval_has_self_referencing_transition();
                    //     permutations.push(permutation);
                    // }
                    // check num holds
                    // let tr_used = self.transition_table.transitions_used(self.n_states);
                    // let test = pre_decider::check_only_one_direction(tr_used);
                    // if !test {
                    //     println!("First Left{}", permutation);
                    //     // todo!()
                    // }
                    // There is no hold in A0
                    if num_hold_a1 + num_hold_other_lines != 1 {
                        self.pre_decider_count_batch
                            .num_not_exactly_one_hold_condition += 1;
                        // let tr_used = self.transition_table.transitions_used(self.n_states);
                        // let old = count_hold_transitions(tr_used);
                        // let new = num_hold_a1 + num_hold_other_lines;
                        // if old != new {
                        //     println!(
                        //         "old {old}, new {new}, hold: {num_hold_other_lines}, id {id} {}",
                        //         permutation.to_standard_tm_text_format()
                        //     );
                        //     let tr3_used =
                        //         &self.transition_table.transitions[range_3_to_n_states.clone()];
                        //     num_hold_other_lines = count_hold_transitions(tr3_used);
                        //     println!(
                        //         "old {old}, new {new}, hold: {num_hold_other_lines}, {}",
                        //         permutation.to_standard_tm_text_format()
                        //     );
                        //     todo!();
                        // }
                        #[cfg(feature = "bb_generator_longest_skip_chain")]
                        self.longest_skip_chain.add_counter(
                            &permutation,
                            PreDeciderReason::NotExactlyOneHoldCondition,
                        );
                    } else {
                        // run pre-decider check
                        let check_pre = self.check_pre_decider();
                        #[cfg(feature = "bb_generator_longest_skip_chain")]
                        match check_pre {
                            PreDeciderReason::None => {
                                self.longest_skip_chain.update_max(id - 1);
                                if self.longest_skip_chain.counter > 1000 {
                                    println!(
                                        "Found chain: {}, {}",
                                        self.longest_skip_chain.counter,
                                        self.longest_skip_chain.machines_max_to_string(4)
                                    );
                                }
                                self.longest_skip_chain.reset_counter();
                            }
                            _ => {
                                self.longest_skip_chain.add_counter(&permutation, check_pre);
                                println!("Pre: {id}: {}", permutation.to_standard_tm_text_format())
                            }
                        }
                        match check_pre {
                            // store machine only in this case
                            PreDeciderReason::None => {
                                permutation.set_eval_has_self_referencing_transition();
                                permutations.push(permutation);
                                #[cfg(feature = "bb_print_non_pre_perm")]
                                println!(
                                    "Perm: {id}: {}",
                                    permutation.to_standard_tm_text_format()
                                );
                            }
                            PreDeciderReason::NotAllStatesUsed => {
                                self.pre_decider_count_batch.num_not_all_states_used += 1;
                            }
                            PreDeciderReason::NotExactlyOneHoldCondition => {
                                self.pre_decider_count_batch
                                    .num_not_exactly_one_hold_condition += 1;
                            }
                            PreDeciderReason::OnlyOneDirection => {
                                self.pre_decider_count_batch.num_only_one_direction += 1;
                            }
                            PreDeciderReason::SimpleStartCycle => {
                                self.pre_decider_count_batch.num_simple_start_cycle += 1;
                            }
                            PreDeciderReason::StartRecursive => {
                                // This one does not happen here, it is included in "not generated".
                                self.pre_decider_count_batch.num_start_recursive += 1;
                            }
                            PreDeciderReason::NotStartStateBRight => {
                                // This one does not happen here, it is included in "not generated".
                                self.pre_decider_count_batch.num_not_start_state_b_right += 1;
                            }
                            PreDeciderReason::WritesOnlyZero => {
                                self.pre_decider_count_batch.num_writes_only_zero += 1;
                            }
                        }
                    }
                    id += 1;
                    if id == self.limit {
                        // total maximum reached
                        self.id_next = id;
                        // not generated = size of batch - generated permutations - eliminated permutations
                        self.pre_decider_count_batch.num_not_generated = self.limit
                            - self.id_batch_start()
                            - permutations.len() as u64
                            - self.pre_decider_count_batch.num_total();
                        return (permutations, true);
                    }
                }
                // adjust id back to normal count
                id += ids_left_out;
                if id >= self.limit {
                    // total maximum reached
                    self.id_next = id;
                    // not generated = size of batch - generated permutations - eliminated permutations
                    self.pre_decider_count_batch.num_not_generated = self.limit
                        - self.id_batch_start()
                        - permutations.len() as u64
                        - self.pre_decider_count_batch.num_total();
                    return (permutations, true);
                }
            }
            // subtract jump to 0RB
            self.id_next = id - 2;
            // self.pre_decider_count.num_not_generated += ids_not_generated_per_round;

            // update line two, permutations state B (still separate for performance)
            self.fields[4] += 1;
            if self.fields[4] < num_tr_permutations {
                self.transition_table.transitions[4] = self.tr_permutations[self.fields[4]];
            } else {
                // set field back to first option
                self.fields[4] = 0;
                self.transition_table.transitions[4] = self.tr_permutations[0];
                'outer: loop {
                    self.field_no += 1;
                    if self.field_no == self.n_fields {
                        // all variants created
                        is_last_batch = true;
                        // println!("last id: {}", self.id_next);
                        break 'creation;
                    }
                    self.fields[self.field_no] += 1;
                    if self.fields[self.field_no] < num_tr_permutations {
                        // set next field with next permutation
                        self.transition_table.transitions[self.field_no] =
                            self.tr_permutations[self.fields[self.field_no]];
                        loop {
                            self.field_no -= 1;
                            if self.field_no == 4 {
                                break 'outer;
                            } else {
                                // set previous field back to first option
                                self.fields[self.field_no] = 0;
                                self.transition_table.transitions[self.field_no] =
                                    self.tr_permutations[0];
                            }
                        }
                    }
                }
            }
            if id >= self.id_batch_last {
                break;
            }
            let tr3_used = &self.transition_table.transitions[range_3_to_n_states.clone()];
            num_hold_other_lines = count_hold_transitions(tr3_used);
        }

        self.pre_decider_count_batch.num_not_generated = (self.batch_size - permutations.len())
            as u64
            - self.pre_decider_count_batch.num_total();
        // self.pre_decider_count_total
        //     .add_pre_decider_count(&self.pre_decider_count_batch);
        (permutations, is_last_batch)
    }

    /// The given limit of machines to generate or (if smaller) the maximum number of machines for the number of states.
    fn limit(&self) -> u64 {
        self.limit
    }

    fn pre_decider_count(&self) -> PreDeciderCount {
        self.pre_decider_count_batch
    }

    fn check_generator_batch_size_request_single_thread(&mut self) {
        if self.batch_size != BATCH_SIZE_REQUEST_SINGLE_THREAD {
            // self.config.generator_batch_size_request_full = BATCH_SIZE_REQUEST_SINGLE_THREAD;
            let batch_size = Self::calc_batch_size(BATCH_SIZE_REQUEST_SINGLE_THREAD, self.n_states);
            // self.num_batches = ((self.limit + batch_size as u64 - 1) / batch_size as u64) as usize;
            self.num_batches = self.limit.div_ceil(batch_size as u64) as usize;
            self.batch_size = batch_size;
        }
    }

    fn num_eliminated(&self) -> u64 {
        self.pre_decider_count().num_total()
    }
}

impl DataProvider for GeneratorReduced {
    fn name(&self) -> &str {
        "Generator Reduced"
    }

    fn machine_batch_next(&mut self) -> ResultDataProvider {
        let (machines, is_last_batch) = self.generate_permutation_batch_next();
        #[cfg(feature = "bb_generator_longest_skip_chain")]
        {
            self.longest_skip_chain.update_max(self.id_batch_last);
            if self.longest_skip_chain.max > self.longest_skip_chain.max_last_info {
                println!("New Longest Chain: {}", self.longest_skip_chain);
                self.longest_skip_chain.max_last_info = self.longest_skip_chain.max;
            }
            if is_last_batch {
                {
                    println!("Longest Chain: {}", self.longest_skip_chain);
                    println!("{}", self.longest_skip_chain.machines_max_to_string(0));
                }
            }
        }
        self.batch_no += 1;
        let end_reason = if is_last_batch {
            EndReason::IsLastBatch
        } else {
            EndReason::None
        };
        Ok(DataProviderBatch {
            batch_no: self.batch_no - 1,
            machines,
            pre_decider_count: Some(self.pre_decider_count_batch),
            end_reason,
        })
    }

    fn batch_size(&self) -> usize {
        self.batch_size
    }

    /// The total number of batches to create all permutations.
    fn num_batches(&self) -> usize {
        self.num_batches
    }

    // fn config(&self) -> &Config {
    //     &self.config
    // }

    fn num_machines_total(&self) -> u64 {
        self.limit
    }

    fn requires_pre_decider_check(&self) -> PreDeciderRun {
        PreDeciderRun::DoNotRun
    }

    fn returns_pre_decider_count(&self) -> bool {
        false
    }

    fn set_batch_size_for_num_threads(&mut self, num_threads: usize) {
        // TODO fine tune
        if num_threads == 1 {
            self.check_generator_batch_size_request_single_thread();
        }
    }
}

impl DataProviderThreaded for GeneratorReduced {
    fn new_from_data_provider(&self) -> Self {
        let mut transition_table = TransitionTableSymbol2::new_default(self.n_states);
        // set all in set to the first variant
        transition_table.transitions[2..2 + self.n_states * 2].fill(self.tr_permutations[0]);

        Self {
            id_next: 0,
            id_batch_last: 0,
            batch_no: 0,
            n_machines: self.n_machines,
            batch_size: self.batch_size,
            limit: self.limit,
            num_batches: self.num_batches,
            tr_permutations: self.tr_permutations.clone(),
            transition_table,
            n_fields: self.n_fields,
            fields: [0; (MAX_STATES + 1) * 2],
            field_no: 4,
            pre_decider_count_batch: Default::default(),
            n_states: self.n_states,
            #[cfg(feature = "bb_generator_longest_skip_chain")]
            longest_skip_chain: Default::default(),
        }
    }

    fn batch_no(&mut self, batch_no: usize) -> DataProviderBatch {
        self.batch_no = batch_no;
        let (machines, is_last_batch) = self.generate_permutation_batch_no(batch_no);
        let end_reason = if is_last_batch {
            EndReason::IsLastBatch
        } else {
            EndReason::None
        };
        DataProviderBatch {
            batch_no: self.batch_no,
            machines,
            pre_decider_count: Some(self.pre_decider_count_batch),
            end_reason,
        }
    }
}

/// long running tests,
/// use cargo test --release generator_reduced
#[cfg(test)]
mod tests {
    use crate::{
        config::Config,
        decider::DeciderStandard,
        decider_engine::{
            batch_run_decider_chain_data_provider_single_thread,
            batch_run_decider_chain_threaded_data_provider_multi_thread,
        },
        decider_result::result_max_steps_known,
        generator_full::GeneratorFull,
    };

    use super::*;

    #[test]
    fn generator_reduced_direct_access_batch_no() {
        let config = Config::builder(4)
            .generator_full_batch_size_request(10_000)
            .generator_reduced_batch_size_request(10_000)
            .machine_limit(10_000_000)
            .build();
        let mut mr = Machine::default();
        let mut batch_no = 0;
        let mut generator_reduced = GeneratorReduced::new(&config);
        loop {
            let (machines, is_finished) = generator_reduced.generate_permutation_batch_next();
            if let Some(m) = machines.first() {
                mr = m.clone();
            }
            if is_finished {
                break;
            }
            batch_no += 1;
        }

        // check direct batch access
        let mut g = GeneratorReduced::new(&config);
        let (machines, _) = g.generate_permutation_batch_no(batch_no);
        let m2 = machines.first().unwrap().clone();
        // println!("m reduced {}: {}", mr.id(), mr.to_standard_tm_text_format());
        // println!("{}", m2.to_standard_tm_text_format());
        assert_eq!(mr, m2);

        // check expected permutation
        // let m3 =
        //     Machine::from_standard_tm_text_format(9996783, "1RB---_0LC1LB_0RA1RD_0RA0RA").unwrap();
        // assert_eq!(m1, m3);

        // compare with GeneratorFull
        let mut g = GeneratorFull::new(&config);
        let (mut machines, _) = g.generate_permutation_batch_no(batch_no);
        for mf in machines.iter_mut() {
            if mf.id() == mr.id() {
                mf.set_eval_has_self_referencing_transition();
                // println!("m full    {}: {}", mf.id(), mf.to_standard_tm_text_format());
                assert_eq!(mr, *mf);
                return;
            }
        }
        panic!("Machine with ID {} not found!", mr.id());
    }

    #[test]
    fn decider_generator_reduced_bb2() {
        run_test_decider_generator_reduced(2);
    }

    #[test]
    fn compare_generator_reduced_with_full_for_bb3() {
        let config = Config::builder(3).machine_limit(500_000).build();
        let mut generator = GeneratorReduced::new(&config);
        let (machines_reduced, _) = generator.generate_permutation_batch_next();
        let mut generator = GeneratorFull::new(&config);
        let (mut machines_full, _) = generator.generate_permutation_batch_next();

        let mut start_id = 0;
        for mr in machines_reduced {
            for mf in machines_full[start_id..].iter_mut() {
                if mf.id() == mr.id() {
                    start_id = mf.id() as usize;
                    mf.set_eval_has_self_referencing_transition();
                    // if mr != *mf {
                    //     println!("r {}: {}", mr.id(), mr.to_standard_tm_text_format());
                    //     println!("f {}: {}", mf.id(), mf.to_standard_tm_text_format());
                    // }
                    assert_eq!(mr, *mf);
                }
            }
        }
    }

    #[test]
    fn decider_generator_reduced_bb3() {
        run_test_decider_generator_reduced(3);
    }

    #[test]
    fn decider_generator_reduced_threaded_bb3() {
        run_test_decider_generator_reduced_threaded(3);
    }

    /// This is not a performance test, it only evaluates 350 million machines.
    /// Long running test: run this only in release mode from command line: \
    /// cargo test --release test_decider_generator_reduced_bb4
    #[test]
    fn decider_generator_reduced_bb4() {
        run_test_decider_generator_reduced(4);
    }

    /// This is not a performance test, it only evaluates 350 million machines.
    /// cargo test --release test_decider_generator_reduced_threaded_bb4
    #[test]
    fn decider_generator_reduced_threaded_bb4() {
        run_test_decider_generator_reduced_threaded(4);
    }

    fn run_test_decider_generator_reduced(n_states: usize) {
        let config = config_bench(n_states);
        let dc = DeciderStandard::Cycler.decider_config(&config);
        let generator = GeneratorReduced::new(&config);
        let result = batch_run_decider_chain_data_provider_single_thread(&vec![dc], generator);
        println!("{}", result);
        println!("{}", result.machines_max_steps_to_string(10));
        assert_eq!(result_max_steps_known(n_states), result.steps_max());
    }

    fn run_test_decider_generator_reduced_threaded(n_states: usize) {
        let config = config_bench(n_states);
        let dc = DeciderStandard::Cycler.decider_config(&config);
        let generator = GeneratorReduced::new(&config);
        let result =
            batch_run_decider_chain_threaded_data_provider_multi_thread(&vec![dc], generator);
        // println!("{}", result);
        assert_eq!(result_max_steps_known(n_states), result.steps_max());
    }

    fn config_bench(n_states: usize) -> Config {
        Config::builder(n_states)
            // .generator_batch_size_request_full(GENERATOR_BATCH_SIZE_REQUEST_FULL)
            // .generator_batch_size_request_reduced(GENERATOR_BATCH_SIZE_REQUEST_REDUCED)
            .machine_limit(200_000_000)
            // .cpu_utilization(100)
            .build()
    }
}

#[cfg(feature = "bb_generator_longest_skip_chain")]
#[allow(dead_code)]
#[derive(Debug)]
pub(crate) struct Counter {
    pub machine_id_first: u64,
    pub machine_id_last: u64,
    pub counter: usize,
    pub max: usize,
    pub max_last_info: usize,
    pub add_max_to_total_if_higher_than: usize,
    pub total: usize,
    pub store_max: usize,
    pub machines: Vec<MachineInfo>,
    pub machines_max: Vec<MachineInfo>,
}

#[cfg(feature = "bb_generator_longest_skip_chain")]
impl Counter {
    pub fn add_counter(&mut self, machine: &Machine, reason: PreDeciderReason) {
        if self.counter == 0 {
            self.machine_id_first = machine.id();
        }
        self.counter += 1;
        let status = crate::status::MachineStatus::EliminatedPreDecider(reason);
        let mi = MachineInfo::new(machine.id(), *machine.transition_table(), status);
        if self.machines.len() < self.store_max {
            self.machines.push(mi);
        } else {
            // if full, store last machine in last position
            self.machines[self.store_max - 1] = mi;
        }
    }

    pub fn reset_counter(&mut self) {
        self.counter = 0;
        self.machines.clear();
    }

    pub fn update_max(&mut self, machine_id_last: u64) {
        if self.counter >= self.add_max_to_total_if_higher_than {
            self.total += self.counter;
            self.machines_max = std::mem::take(&mut self.machines);
        }
        if self.counter > self.max {
            self.max = self.counter;
            // self.machine_id_first = machine_id_last - self.counter as u64 + 1;
        }
        self.machine_id_last = machine_id_last;
    }

    pub fn machines_max_to_string(&self, max_machines: usize) -> String {
        // println!("Longest Chain: {}", self.longest_skip_chain);
        let mut ms = Vec::new();
        if max_machines == 0 {
            for m in self.machines_max.iter() {
                ms.push(m.to_string());
            }
        } else {
            for m in self.machines_max.iter().take(max_machines) {
                ms.push(m.to_string());
            }
        }
        // last machine
        if let Some(last) = self.machines_max.last() {
            ms.push(last.to_string());
        }
        ms.join("\n")
    }
}

#[cfg(feature = "bb_generator_longest_skip_chain")]
impl Default for Counter {
    fn default() -> Self {
        Self {
            machine_id_first: Default::default(),
            machine_id_last: Default::default(),
            counter: Default::default(),
            max: Default::default(),
            max_last_info: Default::default(),
            add_max_to_total_if_higher_than: 500,
            total: Default::default(),
            store_max: 100,
            machines: Default::default(),
            machines_max: Default::default(),
        }
    }
}

#[cfg(feature = "bb_generator_longest_skip_chain")]
impl std::fmt::Display for Counter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Start machine no. {}, last no. {}, max length: {}, reasonable total jump: {}",
            self.machine_id_first, self.machine_id_last, self.max, self.total
        )
    }
}
